baseURL = "http://example.com/"
languageCode = "en-us"
title = "Wolverine_Systems"
theme = "minimal"
#disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "RW"
    description = "Caffeinated Imagineering Projects"
    githubUsername = "#"
    accent = "#494f5c"
    showBorder = true
    #backgroundColor = "#494f5c"
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    #header_background = "img/logo.png"
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/iotprojects/"
    name = "IoT Projects"
    weight = 3

[[menu.main]]
    url = "/uavprojects/"
    name = "UAV Projects"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:ronnie.wong@wolverinesystems.ca"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/wolverinesystems/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/wolverinesys/"
    name = "twitter"
    weight = 3

#[[menu.icon]]
#    url = "https://www.linkedin.com/in/username/"
#    name = "linkedin"
#    weight = 4

#[[menu.icon]]
#    url = "https://www.stackoverflow.com/username/"
#    name = "stack-overflow"
#    weight = 5
